//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"categoria")]
    public partial class Categoria : XPLiteObject
    {
        int fIdCategoria;
        [Key(true)]
        [Persistent(@"idCategoria")]
        public int IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<int>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        string fCategoria1;
        [Persistent(@"Categoria")]
        public string Categoria1
        {
            get { return fCategoria1; }
            set { SetPropertyValue<string>(nameof(Categoria1), ref fCategoria1, value); }
        }
        string fCtaDebito;
        [Size(20)]
        public string CtaDebito
        {
            get { return fCtaDebito; }
            set { SetPropertyValue<string>(nameof(CtaDebito), ref fCtaDebito, value); }
        }
        string fCtaCredito;
        [Size(20)]
        public string CtaCredito
        {
            get { return fCtaCredito; }
            set { SetPropertyValue<string>(nameof(CtaCredito), ref fCtaCredito, value); }
        }
        [Association(@"ProductoReferencesCategoria")]
        public XPCollection<Producto> Productoes { get { return GetCollection<Producto>(nameof(Productoes)); } }
    }

}
