//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"municipio")]
    public partial class Municipio : XPLiteObject
    {
        int fIdMunicipio;
        [Key(true)]
        [Persistent(@"idMunicipio")]
        public int IdMunicipio
        {
            get { return fIdMunicipio; }
            set { SetPropertyValue<int>(nameof(IdMunicipio), ref fIdMunicipio, value); }
        }
        string fCodMunicipio;
        [Size(10)]
        [Persistent(@"codMunicipio")]
        public string CodMunicipio
        {
            get { return fCodMunicipio; }
            set { SetPropertyValue<string>(nameof(CodMunicipio), ref fCodMunicipio, value); }
        }
        string fMunicipio1;
        [Size(50)]
        [Persistent(@"Municipio")]
        public string Municipio1
        {
            get { return fMunicipio1; }
            set { SetPropertyValue<string>(nameof(Municipio1), ref fMunicipio1, value); }
        }
        sbyte fIdEstado;
        [Persistent(@"idEstado")]
        public sbyte IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<sbyte>(nameof(IdEstado), ref fIdEstado, value); }
        }
        int fIdNivel;
        [Persistent(@"idNivel")]
        public int IdNivel
        {
            get { return fIdNivel; }
            set { SetPropertyValue<int>(nameof(IdNivel), ref fIdNivel, value); }
        }
    }

}
