//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"ordendetalle")]
    public partial class Ordendetalle : XPLiteObject
    {
        int fIdOrdenDetalle;
        [Key(true)]
        [Persistent(@"idOrdenDetalle")]
        public int IdOrdenDetalle
        {
            get { return fIdOrdenDetalle; }
            set { SetPropertyValue<int>(nameof(IdOrdenDetalle), ref fIdOrdenDetalle, value); }
        }
        int fIdOrden;
        [Persistent(@"idOrden")]
        public int IdOrden
        {
            get { return fIdOrden; }
            set { SetPropertyValue<int>(nameof(IdOrden), ref fIdOrden, value); }
        }
        int fIdProducto;
        [Persistent(@"idProducto")]
        public int IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<int>(nameof(IdProducto), ref fIdProducto, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio;
        [Persistent(@"precio")]
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
    }

}
