//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fIdProducto;
        [Key(true)]
        [Persistent(@"idProducto")]
        public int IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<int>(nameof(IdProducto), ref fIdProducto, value); }
        }
        Categoria fIdCategoria;
        [Persistent(@"idCategoria")]
        [Association(@"ProductoReferencesCategoria")]
        public Categoria IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<Categoria>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        string fProducto1;
        [Persistent(@"Producto")]
        public string Producto1
        {
            get { return fProducto1; }
            set { SetPropertyValue<string>(nameof(Producto1), ref fProducto1, value); }
        }
        decimal fPrecio;
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
        int fExistencia;
        public int Existencia
        {
            get { return fExistencia; }
            set { SetPropertyValue<int>(nameof(Existencia), ref fExistencia, value); }
        }
        int fExistenciaMinima;
        public int ExistenciaMinima
        {
            get { return fExistenciaMinima; }
            set { SetPropertyValue<int>(nameof(ExistenciaMinima), ref fExistenciaMinima, value); }
        }
        int fExistenciaMaxima;
        public int ExistenciaMaxima
        {
            get { return fExistenciaMaxima; }
            set { SetPropertyValue<int>(nameof(ExistenciaMaxima), ref fExistenciaMaxima, value); }
        }
        int fReservacion;
        public int Reservacion
        {
            get { return fReservacion; }
            set { SetPropertyValue<int>(nameof(Reservacion), ref fReservacion, value); }
        }
        [Association(@"FacturadetalleReferencesProducto")]
        public XPCollection<Facturadetalle> Facturadetalles { get { return GetCollection<Facturadetalle>(nameof(Facturadetalles)); } }
    }

}
