//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"tabladetalle")]
    public partial class Tabladetalle : XPLiteObject
    {
        int fIdLinea;
        [Key(true)]
        [Persistent(@"idLinea")]
        public int IdLinea
        {
            get { return fIdLinea; }
            set { SetPropertyValue<int>(nameof(IdLinea), ref fIdLinea, value); }
        }
        int fIdTabla;
        [Persistent(@"idTabla")]
        public int IdTabla
        {
            get { return fIdTabla; }
            set { SetPropertyValue<int>(nameof(IdTabla), ref fIdTabla, value); }
        }
        string fLinea;
        public string Linea
        {
            get { return fLinea; }
            set { SetPropertyValue<string>(nameof(Linea), ref fLinea, value); }
        }
        string fCodEquivalencia;
        [Size(20)]
        [Persistent(@"codEquivalencia")]
        public string CodEquivalencia
        {
            get { return fCodEquivalencia; }
            set { SetPropertyValue<string>(nameof(CodEquivalencia), ref fCodEquivalencia, value); }
        }
        string fCodPadre;
        [Size(20)]
        [Persistent(@"codPadre")]
        public string CodPadre
        {
            get { return fCodPadre; }
            set { SetPropertyValue<string>(nameof(CodPadre), ref fCodPadre, value); }
        }
        int fIdActivo;
        [Persistent(@"idActivo")]
        public int IdActivo
        {
            get { return fIdActivo; }
            set { SetPropertyValue<int>(nameof(IdActivo), ref fIdActivo, value); }
        }
    }

}
