//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace pruebaDevexpress.venta
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        DateTime fFechaVencimiento;
        [Persistent(@"Fecha_Vencimiento")]
        public DateTime FechaVencimiento
        {
            get { return fFechaVencimiento; }
            set { SetPropertyValue<DateTime>(nameof(FechaVencimiento), ref fFechaVencimiento, value); }
        }
        float fPrecio;
        public float Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<float>(nameof(Precio), ref fPrecio, value); }
        }
        int fEstante;
        public int Estante
        {
            get { return fEstante; }
            set { SetPropertyValue<int>(nameof(Estante), ref fEstante, value); }
        }
        Categoria fIdcategoria;
        [Persistent(@"idcategoria")]
        [Association(@"ProductoReferencesCategoria")]
        public Categoria Idcategoria
        {
            get { return fIdcategoria; }
            set { SetPropertyValue<Categoria>(nameof(Idcategoria), ref fIdcategoria, value); }
        }
        [Association(@"Detalle_ventaReferencesProducto")]
        public XPCollection<Detalle_venta> Detalle_ventas { get { return GetCollection<Detalle_venta>(nameof(Detalle_ventas)); } }
    }

}
