//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace pruebaDevexpress.venta
{

    [Persistent(@"venta")]
    public partial class Venta : XPLiteObject
    {
        int fIdventa;
        [Key(true)]
        [Persistent(@"idVenta")]
        public int Idventa
        {
            get { return fIdventa; }
            set { SetPropertyValue<int>(nameof(Idventa), ref fIdventa, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fDescuento;
        [Size(45)]
        public string Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<string>(nameof(Descuento), ref fDescuento, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        float fMontoTotal;
        [Persistent(@"Monto_total")]
        public float MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<float>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        Cliente fClienteCodigo;
        [Persistent(@"Cliente_codigo")]
        [Association(@"VentaReferencesCliente")]
        public Cliente ClienteCodigo
        {
            get { return fClienteCodigo; }
            set { SetPropertyValue<Cliente>(nameof(ClienteCodigo), ref fClienteCodigo, value); }
        }
        [Association(@"Detalle_ventaReferencesVenta")]
        public XPCollection<Detalle_venta> Detalle_ventas { get { return GetCollection<Detalle_venta>(nameof(Detalle_ventas)); } }
    }

}
