//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"arquedo_diario")]
    public partial class Arquedo_diario : XPLiteObject
    {
        int fIdarqueo;
        [Key(true)]
        [Persistent(@"idarqueo")]
        public int Idarqueo
        {
            get { return fIdarqueo; }
            set { SetPropertyValue<int>(nameof(Idarqueo), ref fIdarqueo, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        double fC1000;
        [Persistent(@"c1000")]
        public double C1000
        {
            get { return fC1000; }
            set { SetPropertyValue<double>(nameof(C1000), ref fC1000, value); }
        }
        double fC500;
        [Persistent(@"c500")]
        public double C500
        {
            get { return fC500; }
            set { SetPropertyValue<double>(nameof(C500), ref fC500, value); }
        }
        double fC200;
        [Persistent(@"c200")]
        public double C200
        {
            get { return fC200; }
            set { SetPropertyValue<double>(nameof(C200), ref fC200, value); }
        }
        double fC100;
        [Persistent(@"c100")]
        public double C100
        {
            get { return fC100; }
            set { SetPropertyValue<double>(nameof(C100), ref fC100, value); }
        }
        double fC50;
        [Persistent(@"c50")]
        public double C50
        {
            get { return fC50; }
            set { SetPropertyValue<double>(nameof(C50), ref fC50, value); }
        }
        double fC20;
        [Persistent(@"c20")]
        public double C20
        {
            get { return fC20; }
            set { SetPropertyValue<double>(nameof(C20), ref fC20, value); }
        }
        double fC10;
        [Persistent(@"c10")]
        public double C10
        {
            get { return fC10; }
            set { SetPropertyValue<double>(nameof(C10), ref fC10, value); }
        }
        double fC5;
        [Persistent(@"c5")]
        public double C5
        {
            get { return fC5; }
            set { SetPropertyValue<double>(nameof(C5), ref fC5, value); }
        }
        double fC1;
        [Persistent(@"c1")]
        public double C1
        {
            get { return fC1; }
            set { SetPropertyValue<double>(nameof(C1), ref fC1, value); }
        }
        double fTotal;
        [Persistent(@"total")]
        public double Total
        {
            get { return fTotal; }
            set { SetPropertyValue<double>(nameof(Total), ref fTotal, value); }
        }
        Cobrador fIdcobrador;
        [Persistent(@"idcobrador")]
        [Association(@"Arquedo_diarioReferencesCobrador")]
        public Cobrador Idcobrador
        {
            get { return fIdcobrador; }
            set { SetPropertyValue<Cobrador>(nameof(Idcobrador), ref fIdcobrador, value); }
        }
        double fDesembolso;
        [Persistent(@"desembolso")]
        public double Desembolso
        {
            get { return fDesembolso; }
            set { SetPropertyValue<double>(nameof(Desembolso), ref fDesembolso, value); }
        }
        double fC50centavos;
        [Persistent(@"c50centavos")]
        public double C50centavos
        {
            get { return fC50centavos; }
            set { SetPropertyValue<double>(nameof(C50centavos), ref fC50centavos, value); }
        }
    }

}
