//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"arreglopago")]
    public partial class Arreglopago : XPLiteObject
    {
        int fIdarreglopago;
        [Key(true)]
        [Persistent(@"idarreglopago")]
        public int Idarreglopago
        {
            get { return fIdarreglopago; }
            set { SetPropertyValue<int>(nameof(Idarreglopago), ref fIdarreglopago, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        DateTime fFechapago;
        [Persistent(@"fechapago")]
        public DateTime Fechapago
        {
            get { return fFechapago; }
            set { SetPropertyValue<DateTime>(nameof(Fechapago), ref fFechapago, value); }
        }
        int fIdcredito;
        [Indexed(Name = @"iidcredito_arreglopago")]
        [Persistent(@"idcredito")]
        public int Idcredito
        {
            get { return fIdcredito; }
            set { SetPropertyValue<int>(nameof(Idcredito), ref fIdcredito, value); }
        }
        sbyte fActivo;
        [Persistent(@"activo")]
        public sbyte Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<sbyte>(nameof(Activo), ref fActivo, value); }
        }
        string fNota;
        [Size(200)]
        [Persistent(@"nota")]
        public string Nota
        {
            get { return fNota; }
            set { SetPropertyValue<string>(nameof(Nota), ref fNota, value); }
        }
    }

}
