//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"autorizar_anulacion")]
    public partial class Autorizar_anulacion : XPLiteObject
    {
        int fIdautorizar;
        [Key(true)]
        [Persistent(@"idautorizar")]
        public int Idautorizar
        {
            get { return fIdautorizar; }
            set { SetPropertyValue<int>(nameof(Idautorizar), ref fIdautorizar, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        int fIdcredito;
        [Indexed(Name = @"iidcredito_autorizar_anulacion")]
        [Persistent(@"idcredito")]
        public int Idcredito
        {
            get { return fIdcredito; }
            set { SetPropertyValue<int>(nameof(Idcredito), ref fIdcredito, value); }
        }
        int fIdusuario1;
        [Indexed(Name = @"iidusuario1_autorizar_anulacion")]
        [Persistent(@"idusuario1")]
        public int Idusuario1
        {
            get { return fIdusuario1; }
            set { SetPropertyValue<int>(nameof(Idusuario1), ref fIdusuario1, value); }
        }
        int fIdusuario2;
        [Indexed(Name = @"iidusuario2_autorizar_anulacion")]
        [Persistent(@"idusuario2")]
        public int Idusuario2
        {
            get { return fIdusuario2; }
            set { SetPropertyValue<int>(nameof(Idusuario2), ref fIdusuario2, value); }
        }
        int fIdusuario3;
        [Indexed(Name = @"iidusuario3_autorizar_anulacion")]
        [Persistent(@"idusuario3")]
        public int Idusuario3
        {
            get { return fIdusuario3; }
            set { SetPropertyValue<int>(nameof(Idusuario3), ref fIdusuario3, value); }
        }
        int fEstado;
        [Persistent(@"estado")]
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        string fComentario;
        [Size(200)]
        [Persistent(@"comentario")]
        public string Comentario
        {
            get { return fComentario; }
            set { SetPropertyValue<string>(nameof(Comentario), ref fComentario, value); }
        }
        DateTime fFecha_resolucion;
        [Persistent(@"fecha_resolucion")]
        public DateTime Fecha_resolucion
        {
            get { return fFecha_resolucion; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_resolucion), ref fFecha_resolucion, value); }
        }
    }

}
