//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"barrio")]
    public partial class Barrio : XPLiteObject
    {
        int fIdbarrio;
        [Key(true)]
        [Persistent(@"idbarrio")]
        public int Idbarrio
        {
            get { return fIdbarrio; }
            set { SetPropertyValue<int>(nameof(Idbarrio), ref fIdbarrio, value); }
        }
        string fNombre;
        [Size(200)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDetalle;
        [Size(200)]
        [Persistent(@"detalle")]
        public string Detalle
        {
            get { return fDetalle; }
            set { SetPropertyValue<string>(nameof(Detalle), ref fDetalle, value); }
        }
    }

}
