//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"bitacora_credito")]
    public partial class Bitacora_credito : XPLiteObject
    {
        int fIdbitacora;
        [Key(true)]
        [Persistent(@"idbitacora")]
        public int Idbitacora
        {
            get { return fIdbitacora; }
            set { SetPropertyValue<int>(nameof(Idbitacora), ref fIdbitacora, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        int fMovimiento;
        [Persistent(@"movimiento")]
        public int Movimiento
        {
            get { return fMovimiento; }
            set { SetPropertyValue<int>(nameof(Movimiento), ref fMovimiento, value); }
        }
        int fIdcredito;
        [Indexed(Name = @"iidcredito_bitacora_credito")]
        [Persistent(@"idcredito")]
        public int Idcredito
        {
            get { return fIdcredito; }
            set { SetPropertyValue<int>(nameof(Idcredito), ref fIdcredito, value); }
        }
        int fIdusuario;
        [Indexed(Name = @"iidusuario_bitacora_credito")]
        [Persistent(@"idusuario")]
        public int Idusuario
        {
            get { return fIdusuario; }
            set { SetPropertyValue<int>(nameof(Idusuario), ref fIdusuario, value); }
        }
    }

}
