//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"cobrador")]
    public partial class Cobrador : XPLiteObject
    {
        int fIdCobrador;
        [Key(true)]
        [Persistent(@"idCobrador")]
        public int IdCobrador
        {
            get { return fIdCobrador; }
            set { SetPropertyValue<int>(nameof(IdCobrador), ref fIdCobrador, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        [Association(@"Arquedo_diarioReferencesCobrador")]
        public XPCollection<Arquedo_diario> Arquedo_diarios { get { return GetCollection<Arquedo_diario>(nameof(Arquedo_diarios)); } }
        [Association(@"PrestamoReferencesCobrador")]
        public XPCollection<Prestamo> Prestamoes { get { return GetCollection<Prestamo>(nameof(Prestamoes)); } }
    }

}
