//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"cuotas")]
    public partial class Cuotas : XPLiteObject
    {
        int fCuentaid;
        [Key(true)]
        [Persistent(@"cuentaid")]
        public int Cuentaid
        {
            get { return fCuentaid; }
            set { SetPropertyValue<int>(nameof(Cuentaid), ref fCuentaid, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        float fMonto;
        [Persistent(@"monto")]
        public float Monto
        {
            get { return fMonto; }
            set { SetPropertyValue<float>(nameof(Monto), ref fMonto, value); }
        }
        Prestamo fPrestamo_prestamoid;
        [Persistent(@"prestamo_prestamoid")]
        [Association(@"CuotasReferencesPrestamo")]
        public Prestamo Prestamo_prestamoid
        {
            get { return fPrestamo_prestamoid; }
            set { SetPropertyValue<Prestamo>(nameof(Prestamo_prestamoid), ref fPrestamo_prestamoid, value); }
        }
        int fNum_abono;
        [Persistent(@"num_abono")]
        public int Num_abono
        {
            get { return fNum_abono; }
            set { SetPropertyValue<int>(nameof(Num_abono), ref fNum_abono, value); }
        }
        int fMora;
        [Persistent(@"mora")]
        public int Mora
        {
            get { return fMora; }
            set { SetPropertyValue<int>(nameof(Mora), ref fMora, value); }
        }
        float fSaldo;
        [Persistent(@"saldo")]
        public float Saldo
        {
            get { return fSaldo; }
            set { SetPropertyValue<float>(nameof(Saldo), ref fSaldo, value); }
        }
        float fPendiente;
        [Persistent(@"pendiente")]
        public float Pendiente
        {
            get { return fPendiente; }
            set { SetPropertyValue<float>(nameof(Pendiente), ref fPendiente, value); }
        }
        string fFechahora;
        [Size(45)]
        [Persistent(@"fechahora")]
        public string Fechahora
        {
            get { return fFechahora; }
            set { SetPropertyValue<string>(nameof(Fechahora), ref fFechahora, value); }
        }
    }

}
