//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"failed_jobs")]
    public partial class Failed_jobs : XPLiteObject
    {
        ulong fId;
        [Key]
        [Persistent(@"id")]
        public ulong Id
        {
            get { return fId; }
            set { SetPropertyValue<ulong>(nameof(Id), ref fId, value); }
        }
        string fUuid;
        [Indexed(Name = @"failed_jobs_uuid_unique", Unique = true)]
        [Size(255)]
        [Persistent(@"uuid")]
        public string Uuid
        {
            get { return fUuid; }
            set { SetPropertyValue<string>(nameof(Uuid), ref fUuid, value); }
        }
        string fConnection;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"connection")]
        public string Connection
        {
            get { return fConnection; }
            set { SetPropertyValue<string>(nameof(Connection), ref fConnection, value); }
        }
        string fQueue;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"queue")]
        public string Queue
        {
            get { return fQueue; }
            set { SetPropertyValue<string>(nameof(Queue), ref fQueue, value); }
        }
        string fPayload;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"payload")]
        public string Payload
        {
            get { return fPayload; }
            set { SetPropertyValue<string>(nameof(Payload), ref fPayload, value); }
        }
        string fException;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"exception")]
        public string Exception
        {
            get { return fException; }
            set { SetPropertyValue<string>(nameof(Exception), ref fException, value); }
        }
    }

}
