//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"model_has_roles")]
    public partial class Model_has_roles : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("role_id")]
            public ulong Role_id { get; set; }
            [Size(255)]
            [Persistent("model_type")]
            public string Model_type { get; set; }
            [Persistent("model_id")]
            public ulong Model_id { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
