//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"pagos")]
    public partial class Pagos : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        DateTime fFecha_pago;
        [Persistent(@"fecha_pago")]
        public DateTime Fecha_pago
        {
            get { return fFecha_pago; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_pago), ref fFecha_pago, value); }
        }
        float fMonto;
        [Persistent(@"monto")]
        public float Monto
        {
            get { return fMonto; }
            set { SetPropertyValue<float>(nameof(Monto), ref fMonto, value); }
        }
        float fPagado;
        [Persistent(@"pagado")]
        public float Pagado
        {
            get { return fPagado; }
            set { SetPropertyValue<float>(nameof(Pagado), ref fPagado, value); }
        }
        float fPendiente;
        [Persistent(@"pendiente")]
        public float Pendiente
        {
            get { return fPendiente; }
            set { SetPropertyValue<float>(nameof(Pendiente), ref fPendiente, value); }
        }
        Prestamo fPrestamo;
        [Persistent(@"prestamo")]
        [Association(@"PagosReferencesPrestamo")]
        public Prestamo Prestamo
        {
            get { return fPrestamo; }
            set { SetPropertyValue<Prestamo>(nameof(Prestamo), ref fPrestamo, value); }
        }
    }

}
