//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"prestamo")]
    public partial class Prestamo : XPLiteObject
    {
        int fPrestamoid;
        [Key(true)]
        [Persistent(@"prestamoid")]
        public int Prestamoid
        {
            get { return fPrestamoid; }
            set { SetPropertyValue<int>(nameof(Prestamoid), ref fPrestamoid, value); }
        }
        float fMonto;
        [Persistent(@"monto")]
        public float Monto
        {
            get { return fMonto; }
            set { SetPropertyValue<float>(nameof(Monto), ref fMonto, value); }
        }
        float fInteres;
        [Persistent(@"interes")]
        public float Interes
        {
            get { return fInteres; }
            set { SetPropertyValue<float>(nameof(Interes), ref fInteres, value); }
        }
        int fPlazo;
        [Persistent(@"plazo")]
        public int Plazo
        {
            get { return fPlazo; }
            set { SetPropertyValue<int>(nameof(Plazo), ref fPlazo, value); }
        }
        DateTime fFechainicial;
        [Persistent(@"fechainicial")]
        public DateTime Fechainicial
        {
            get { return fFechainicial; }
            set { SetPropertyValue<DateTime>(nameof(Fechainicial), ref fFechainicial, value); }
        }
        float fMonto_a_pagar;
        [Persistent(@"monto_a_pagar")]
        public float Monto_a_pagar
        {
            get { return fMonto_a_pagar; }
            set { SetPropertyValue<float>(nameof(Monto_a_pagar), ref fMonto_a_pagar, value); }
        }
        float fMonto_pendiente;
        [Persistent(@"monto_pendiente")]
        public float Monto_pendiente
        {
            get { return fMonto_pendiente; }
            set { SetPropertyValue<float>(nameof(Monto_pendiente), ref fMonto_pendiente, value); }
        }
        bool fActivo;
        [Persistent(@"activo")]
        public bool Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<bool>(nameof(Activo), ref fActivo, value); }
        }
        Cliente fCliente_clienteid;
        [Persistent(@"cliente_clienteid")]
        [Association(@"PrestamoReferencesCliente")]
        public Cliente Cliente_clienteid
        {
            get { return fCliente_clienteid; }
            set { SetPropertyValue<Cliente>(nameof(Cliente_clienteid), ref fCliente_clienteid, value); }
        }
        Cobrador fCobrador_idCobrador;
        [Persistent(@"cobrador_idCobrador")]
        [Association(@"PrestamoReferencesCobrador")]
        public Cobrador Cobrador_idCobrador
        {
            get { return fCobrador_idCobrador; }
            set { SetPropertyValue<Cobrador>(nameof(Cobrador_idCobrador), ref fCobrador_idCobrador, value); }
        }
        Cuenta fCuenta_idCuenta;
        [Persistent(@"cuenta_idCuenta")]
        [Association(@"PrestamoReferencesCuenta")]
        public Cuenta Cuenta_idCuenta
        {
            get { return fCuenta_idCuenta; }
            set { SetPropertyValue<Cuenta>(nameof(Cuenta_idCuenta), ref fCuenta_idCuenta, value); }
        }
        Prestamo fRenovacion;
        [Persistent(@"renovacion")]
        [Association(@"PrestamoReferencesPrestamo")]
        public Prestamo Renovacion
        {
            get { return fRenovacion; }
            set { SetPropertyValue<Prestamo>(nameof(Renovacion), ref fRenovacion, value); }
        }
        string fMoneda;
        [Size(45)]
        [Persistent(@"moneda")]
        public string Moneda
        {
            get { return fMoneda; }
            set { SetPropertyValue<string>(nameof(Moneda), ref fMoneda, value); }
        }
        bool fMalo;
        [Persistent(@"malo")]
        public bool Malo
        {
            get { return fMalo; }
            set { SetPropertyValue<bool>(nameof(Malo), ref fMalo, value); }
        }
        int fTipopago;
        [Persistent(@"tipopago")]
        public int Tipopago
        {
            get { return fTipopago; }
            set { SetPropertyValue<int>(nameof(Tipopago), ref fTipopago, value); }
        }
        DateTime fFechafin;
        [Persistent(@"fechafin")]
        public DateTime Fechafin
        {
            get { return fFechafin; }
            set { SetPropertyValue<DateTime>(nameof(Fechafin), ref fFechafin, value); }
        }
        int fEstado;
        [Persistent(@"estado")]
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        int fDia_pago;
        [Persistent(@"dia_pago")]
        public int Dia_pago
        {
            get { return fDia_pago; }
            set { SetPropertyValue<int>(nameof(Dia_pago), ref fDia_pago, value); }
        }
        DateTime fFecha_creacion;
        [Persistent(@"fecha_creacion")]
        public DateTime Fecha_creacion
        {
            get { return fFecha_creacion; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_creacion), ref fFecha_creacion, value); }
        }
        float fMonto_cuota;
        [Persistent(@"monto_cuota")]
        public float Monto_cuota
        {
            get { return fMonto_cuota; }
            set { SetPropertyValue<float>(nameof(Monto_cuota), ref fMonto_cuota, value); }
        }
        double fPendiente;
        [Persistent(@"pendiente")]
        public double Pendiente
        {
            get { return fPendiente; }
            set { SetPropertyValue<double>(nameof(Pendiente), ref fPendiente, value); }
        }
        int fDia_pago1;
        [Persistent(@"dia_pago1")]
        public int Dia_pago1
        {
            get { return fDia_pago1; }
            set { SetPropertyValue<int>(nameof(Dia_pago1), ref fDia_pago1, value); }
        }
        int fDia_pago2;
        [Persistent(@"dia_pago2")]
        public int Dia_pago2
        {
            get { return fDia_pago2; }
            set { SetPropertyValue<int>(nameof(Dia_pago2), ref fDia_pago2, value); }
        }
        int fSeguro;
        [Persistent(@"seguro")]
        public int Seguro
        {
            get { return fSeguro; }
            set { SetPropertyValue<int>(nameof(Seguro), ref fSeguro, value); }
        }
        int fCantidad_cuotas;
        [Persistent(@"cantidad_cuotas")]
        public int Cantidad_cuotas
        {
            get { return fCantidad_cuotas; }
            set { SetPropertyValue<int>(nameof(Cantidad_cuotas), ref fCantidad_cuotas, value); }
        }
        string fCampo_nuevo;
        [Size(45)]
        [Persistent(@"campo_nuevo")]
        public string Campo_nuevo
        {
            get { return fCampo_nuevo; }
            set { SetPropertyValue<string>(nameof(Campo_nuevo), ref fCampo_nuevo, value); }
        }
        [Association(@"CuotasReferencesPrestamo")]
        public XPCollection<Cuotas> CuotasCollection { get { return GetCollection<Cuotas>(nameof(CuotasCollection)); } }
        [Association(@"MoraReferencesPrestamo")]
        public XPCollection<Mora> Moras { get { return GetCollection<Mora>(nameof(Moras)); } }
        [Association(@"PagosReferencesPrestamo")]
        public XPCollection<Pagos> PagosCollection { get { return GetCollection<Pagos>(nameof(PagosCollection)); } }
        [Association(@"PrestamoReferencesPrestamo")]
        public XPCollection<Prestamo> PrestamoCollection { get { return GetCollection<Prestamo>(nameof(PrestamoCollection)); } }
    }

}
