//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"proforma")]
    public partial class Proforma : XPLiteObject
    {
        int fIdproforma;
        [Key(true)]
        [Persistent(@"idproforma")]
        public int Idproforma
        {
            get { return fIdproforma; }
            set { SetPropertyValue<int>(nameof(Idproforma), ref fIdproforma, value); }
        }
        string fMonto;
        [Size(45)]
        [Persistent(@"monto")]
        public string Monto
        {
            get { return fMonto; }
            set { SetPropertyValue<string>(nameof(Monto), ref fMonto, value); }
        }
        string fFecha;
        [Size(45)]
        [Persistent(@"fecha")]
        public string Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<string>(nameof(Fecha), ref fFecha, value); }
        }
        string fNumcuota;
        [Size(45)]
        [Persistent(@"numcuota")]
        public string Numcuota
        {
            get { return fNumcuota; }
            set { SetPropertyValue<string>(nameof(Numcuota), ref fNumcuota, value); }
        }
        string fSaldo;
        [Size(45)]
        [Persistent(@"saldo")]
        public string Saldo
        {
            get { return fSaldo; }
            set { SetPropertyValue<string>(nameof(Saldo), ref fSaldo, value); }
        }
    }

}
