//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"telefono")]
    public partial class Telefono : XPLiteObject
    {
        int fIdtelefono;
        [Key(true)]
        [Persistent(@"idtelefono")]
        public int Idtelefono
        {
            get { return fIdtelefono; }
            set { SetPropertyValue<int>(nameof(Idtelefono), ref fIdtelefono, value); }
        }
        string fNumero;
        [Size(20)]
        [Persistent(@"numero")]
        public string Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<string>(nameof(Numero), ref fNumero, value); }
        }
        string fDescripcion;
        [Size(45)]
        [Persistent(@"descripcion")]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        Cliente fClienteid;
        [Persistent(@"clienteid")]
        [Association(@"TelefonoReferencesCliente")]
        public Cliente Clienteid
        {
            get { return fClienteid; }
            set { SetPropertyValue<Cliente>(nameof(Clienteid), ref fClienteid, value); }
        }
    }

}
