//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"users")]
    public partial class Users : XPLiteObject
    {
        ulong fId;
        [Key]
        [Persistent(@"id")]
        public ulong Id
        {
            get { return fId; }
            set { SetPropertyValue<ulong>(nameof(Id), ref fId, value); }
        }
        string fName;
        [Size(255)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fEmail;
        [Indexed(Name = @"users_email_unique", Unique = true)]
        [Size(255)]
        [Persistent(@"email")]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fPassword;
        [Size(255)]
        [Persistent(@"password")]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fRemember_token;
        [Persistent(@"remember_token")]
        public string Remember_token
        {
            get { return fRemember_token; }
            set { SetPropertyValue<string>(nameof(Remember_token), ref fRemember_token, value); }
        }
    }

}
