//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PersonalizarGridControl.credito_mauricio
{

    [Persistent(@"usuario")]
    public partial class Usuario : XPLiteObject
    {
        int fUsuarioid;
        [Key(true)]
        [Persistent(@"usuarioid")]
        public int Usuarioid
        {
            get { return fUsuarioid; }
            set { SetPropertyValue<int>(nameof(Usuarioid), ref fUsuarioid, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fPassword;
        [Size(45)]
        [Persistent(@"password")]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fTipo;
        [Size(45)]
        [Persistent(@"tipo")]
        public string Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<string>(nameof(Tipo), ref fTipo, value); }
        }
    }

}
