//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"area")]
    public partial class Area : XPLiteObject
    {
        int fIdArea;
        [Key(true)]
        [Persistent(@"idArea")]
        public int IdArea
        {
            get { return fIdArea; }
            set { SetPropertyValue<int>(nameof(IdArea), ref fIdArea, value); }
        }
        Area fIdAreaPadre;
        [Persistent(@"idAreaPadre")]
        [Association(@"AreaReferencesArea")]
        public Area IdAreaPadre
        {
            get { return fIdAreaPadre; }
            set { SetPropertyValue<Area>(nameof(IdAreaPadre), ref fIdAreaPadre, value); }
        }
        string fCodArea;
        [Size(10)]
        [Persistent(@"codArea")]
        public string CodArea
        {
            get { return fCodArea; }
            set { SetPropertyValue<string>(nameof(CodArea), ref fCodArea, value); }
        }
        string fCodAreaPadre;
        [Size(10)]
        [Persistent(@"codAreaPadre")]
        public string CodAreaPadre
        {
            get { return fCodAreaPadre; }
            set { SetPropertyValue<string>(nameof(CodAreaPadre), ref fCodAreaPadre, value); }
        }
        string fArea1;
        [Persistent(@"area")]
        public string Area1
        {
            get { return fArea1; }
            set { SetPropertyValue<string>(nameof(Area1), ref fArea1, value); }
        }
        int fOrden;
        [Persistent(@"orden")]
        public int Orden
        {
            get { return fOrden; }
            set { SetPropertyValue<int>(nameof(Orden), ref fOrden, value); }
        }
        int fNivel;
        [Persistent(@"nivel")]
        public int Nivel
        {
            get { return fNivel; }
            set { SetPropertyValue<int>(nameof(Nivel), ref fNivel, value); }
        }
        sbyte fIdEstado;
        [Persistent(@"idEstado")]
        public sbyte IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<sbyte>(nameof(IdEstado), ref fIdEstado, value); }
        }
        [Association(@"AreaReferencesArea")]
        public XPCollection<Area> AreaCollection { get { return GetCollection<Area>(nameof(AreaCollection)); } }
        [Association(@"EmpleadoReferencesArea")]
        public XPCollection<Empleado> Empleadoes { get { return GetCollection<Empleado>(nameof(Empleadoes)); } }
    }

}
