//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"facturadetalle")]
    public partial class Facturadetalle : XPLiteObject
    {
        int fIdFacturaDetalle;
        [Key(true)]
        [Persistent(@"idFacturaDetalle")]
        public int IdFacturaDetalle
        {
            get { return fIdFacturaDetalle; }
            set { SetPropertyValue<int>(nameof(IdFacturaDetalle), ref fIdFacturaDetalle, value); }
        }
        Factura fIdFactura;
        [Persistent(@"idFactura")]
        [Association(@"FacturadetalleReferencesFactura")]
        public Factura IdFactura
        {
            get { return fIdFactura; }
            set { SetPropertyValue<Factura>(nameof(IdFactura), ref fIdFactura, value); }
        }
        Producto fIdProducto;
        [Persistent(@"idProducto")]
        [Association(@"FacturadetalleReferencesProducto")]
        public Producto IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<Producto>(nameof(IdProducto), ref fIdProducto, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio;
        [Persistent(@"precio")]
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
    }

}
