//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"ordenabono")]
    public partial class Ordenabono : XPLiteObject
    {
        int fIdOrdenAbono;
        [Key(true)]
        [Persistent(@"idOrdenAbono")]
        public int IdOrdenAbono
        {
            get { return fIdOrdenAbono; }
            set { SetPropertyValue<int>(nameof(IdOrdenAbono), ref fIdOrdenAbono, value); }
        }
        int fIdOrden;
        [Persistent(@"idOrden")]
        public int IdOrden
        {
            get { return fIdOrden; }
            set { SetPropertyValue<int>(nameof(IdOrden), ref fIdOrden, value); }
        }
        decimal fMontoAbono;
        [Persistent(@"montoAbono")]
        public decimal MontoAbono
        {
            get { return fMontoAbono; }
            set { SetPropertyValue<decimal>(nameof(MontoAbono), ref fMontoAbono, value); }
        }
        DateTime fFechaAbono;
        [Persistent(@"fechaAbono")]
        public DateTime FechaAbono
        {
            get { return fFechaAbono; }
            set { SetPropertyValue<DateTime>(nameof(FechaAbono), ref fFechaAbono, value); }
        }
    }

}
