//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.facturacion
{

    [Persistent(@"tabla")]
    public partial class Tabla : XPLiteObject
    {
        int fIdTabla;
        [Key(true)]
        [Persistent(@"idTabla")]
        public int IdTabla
        {
            get { return fIdTabla; }
            set { SetPropertyValue<int>(nameof(IdTabla), ref fIdTabla, value); }
        }
        string fTabla1;
        [Persistent(@"Tabla")]
        public string Tabla1
        {
            get { return fTabla1; }
            set { SetPropertyValue<string>(nameof(Tabla1), ref fTabla1, value); }
        }
    }

}
